# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vai trò')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Người phỏng vấn',
                'verbose_name_plural': 'Người phỏng vấn',
                'db_table': 'interview_interviewers',
            },
        ),
    ]
