# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment_interview_interviewers', '0001_initial'),
        ('recruitment_interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinterviewer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='recruitment_interviews.interview', verbose_name='Phỏng vấn'),
        ),
        migrations.AddField(
            model_name='interviewinterviewer',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_participations', to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together={('interview', 'interviewer')},
        ),
    ]
