# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(blank=True, null=True, verbose_name='Từ khóa tìm kiếm')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='Bộ lọc')),
                ('results_count', models.IntegerField(blank=True, null=True, verbose_name='Số kết quả')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian tìm kiếm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_search_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm việc làm',
                'verbose_name_plural': 'Lịch sử tìm kiếm việc làm',
                'db_table': 'job_search_history',
                'ordering': ['-searched_at'],
            },
        ),
    ]
