# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiter_skills', '0001_initial'),
        ('candidate_recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mối quan hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to='candidate_recruiters.recruiter', verbose_name='Người xác nhận')),
                ('recruiter_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='candidate_recruiter_skills.recruiterskill', verbose_name='Kỹ năng ứng viên')),
            ],
            options={
                'verbose_name': 'Xác nhận kỹ năng',
                'verbose_name_plural': 'Xác nhận kỹ năng',
                'db_table': 'skill_endorsements',
                'unique_together': {('recruiter_skill', 'endorsed_by')},
            },
        ),
    ]
