# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
        ('geography_addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí hiện tại')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn URL')),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub URL')),
                ('portfolio_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Portfolio URL')),
                ('job_search_status', models.CharField(choices=[('active', 'Đang tìm việc'), ('passive', 'Sẵn sàng cơ hội mới'), ('not_looking', 'Không tìm việc')], db_index=True, default='passive', max_length=20, verbose_name='Trạng thái tìm việc')),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối thiểu mong muốn')),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối đa mong muốn')),
                ('salary_currency', models.CharField(default='VND', max_length=10, verbose_name='Đơn vị tiền tệ')),
                ('available_from_date', models.DateField(blank=True, null=True, verbose_name='Ngày có thể bắt đầu')),
                ('years_of_experience', models.IntegerField(db_index=True, default=0, verbose_name='Số năm kinh nghiệm')),
                ('highest_education_level', models.CharField(blank=True, choices=[('thpt', 'THPT'), ('trung_cap', 'Trung cấp'), ('cao_dang', 'Cao đẳng'), ('dai_hoc', 'Đại học'), ('thac_si', 'Thạc sĩ'), ('tien_si', 'Tiến sĩ'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Trình độ học vấn cao nhất')),
                ('profile_completeness_score', models.IntegerField(default=0, verbose_name='Điểm hoàn thiện hồ sơ')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='Hồ sơ công khai')),
                ('profile_views_count', models.IntegerField(default=0, verbose_name='Lượt xem hồ sơ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='geography_addresses.address', verbose_name='Địa chỉ')),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='company_companies.company', verbose_name='Công ty hiện tại')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Ứng viên',
                'verbose_name_plural': 'Ứng viên',
                'db_table': 'recruiters',
            },
        ),
    ]
