# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=255, verbose_name='Email người nhận')),
                ('subject', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('queued', 'Trong hàng đợi'), ('sent', 'Đã gửi'), ('delivered', 'Đã nhận'), ('opened', 'Đã mở'), ('clicked', 'Đã click'), ('bounced', 'Bị trả lại'), ('failed', 'Thất bại')], db_index=True, default='queued', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày gửi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày mở')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày click')),
            ],
            options={
                'verbose_name': 'Email đã gửi',
                'verbose_name_plural': 'Email đã gửi',
                'db_table': 'sent_emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
