# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_email_templates', '0001_initial'),
        ('email_sent_emails', '0001_initial'),
        ('recruitment_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='recruitment_applications.application', verbose_name='Đơn ứng tuyển'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='email_email_templates.emailtemplate', verbose_name='Mẫu email'),
        ),
    ]
