"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
import time
from pathlib import Path
from urllib.parse import quote
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env by default, regardless of the shell working directory.
# Use DJANGO_ENV_FILE=/path/to/file for explicit local/production overrides.
try:
    env_file = os.getenv("DJANGO_ENV_FILE")
    if env_file:
        load_dotenv(env_file, override=True)
    else:
        load_dotenv(BASE_DIR / ".env", override=False)
except Exception as e:
    print(f"Warning: Could not load .env file: {e}")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return int(value)


def env_float(name, default=0.0):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return float(value)


def env_list(name, default=None):
    value = os.getenv(name, "")
    if not value.strip():
        return list(default or [])
    return [item for item in re.split(r"[\s,]+", value.strip()) if item]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DEBUG", default=True)
SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise RuntimeError("SECRET_KEY must be set when DEBUG=0")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"] if DEBUG else [],
)

if not DEBUG:
    if not ALLOWED_HOSTS:
        raise RuntimeError("DJANGO_ALLOWED_HOSTS must be set when DEBUG=0")
    if (
        SECRET_KEY.startswith("django-insecure-")
        or len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 5
    ):
        raise RuntimeError(
            "SECRET_KEY must be strong and at least 50 characters when DEBUG=0"
        )


# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI server
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # Postgres Full-Text Search
    # Third party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "cloudinary_storage",
    "cloudinary",
    "channels",
    "django_eventstream",
    # ===== Core Domain =====
    "apps.core.users",
    "apps.moderation",
    # ===== Geography Domain =====
    "apps.geography.provinces",
    "apps.geography.communes",
    "apps.geography.addresses",
    # ===== Company Domain =====
    "apps.company.companies.apps.CompaniesConfig",
    "apps.company.industries",
    "apps.company.benefit_categories",
    "apps.company.company_benefits",
    "apps.company.media_types",
    "apps.company.company_media",
    # ===== Recruitment Domain =====
    "apps.recruitment.jobs",
    "apps.recruitment.job_categories",
    # Billing Module
    "apps.billing",
    "apps.recruitment.job_skills",
    "apps.recruitment.job_locations",
    "apps.recruitment.applications",
    "apps.recruitment.application_status_history",
    "apps.recruitment.interviews",
    "apps.recruitment.interview_types",
    "apps.recruitment.saved_jobs",
    "apps.recruitment.job_views",
    # ===== Candidate Domain =====
    "apps.candidate.recruiters",
    "apps.candidate.recruiter_education",
    "apps.candidate.recruiter_experience",
    "apps.candidate.recruiter_skills",
    "apps.candidate.recruiter_certifications",
    "apps.candidate.recruiter_languages",
    "apps.candidate.recruiter_projects",
    "apps.candidate.recruiter_cvs",
    "apps.candidate.cv_templates",
    "apps.candidate.cv_template_categories",
    "apps.candidate.skills",
    "apps.candidate.skill_categories",
    "apps.candidate.languages",
    # ===== Social Domain =====
    "apps.social.company_followers",
    # ===== Communication Domain =====
    "apps.communication.notifications",
    "apps.communication.notification_types",
    "apps.communication.job_alerts",
    "apps.communication.job_alert_skills",
    # ===== Billing Domain =====
    # 'apps.billing.subscription_plans',
    # 'apps.billing.company_subscriptions',
    # 'apps.billing.payment_methods',
    # 'apps.billing.payment_transactions',
    # ===== Email Domain =====
    "apps.email",
    # 'apps.email.email_templates',
    # 'apps.email.email_template_categories',
    # 'apps.email.email_logs',
    # 'apps.email.sent_emails',
    # ===== Blog Domain =====
    "apps.blog",
    # 'apps.blog.blog_posts',
    # 'apps.blog.blog_categories',
    # 'apps.blog.blog_tags',
    # 'apps.blog.blog_post_tags',
    # 'apps.blog.blog_comments',
    # ===== System Domain =====
    "apps.system.system_settings",
    "apps.system.activity_logs",
    "apps.system.activity_log_types",
    "apps.system.file_uploads",
    # ===== Analytics Domain =====
    "apps.system.report_types",
    "apps.system.reports",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "apps.core.security_headers.SecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


def _redis_url(db: int) -> str:
    scheme = "rediss" if env_bool("REDIS_SSL", default=False) else "redis"
    host = os.getenv("REDIS_HOST") or ("localhost" if DEBUG else "redis")
    port = env_int("REDIS_PORT", 6379)
    username = os.getenv("REDIS_USERNAME", "").strip()
    password = os.getenv("REDIS_PASSWORD", "").strip()

    auth = ""
    if username and password:
        auth = f"{quote(username)}:{quote(password)}@"
    elif password:
        auth = f":{quote(password)}@"
    elif username:
        auth = f"{quote(username)}@"

    return f"{scheme}://{auth}{host}:{port}/{db}"


_REDIS_EXPLICITLY_CONFIGURED = any(
    os.getenv(name)
    for name in (
        "REDIS_URL",
        "REDIS_CACHE_URL",
        "CHANNEL_REDIS_URL",
        "CELERY_BROKER_URL",
        "CELERY_RESULT_BACKEND",
        "REDIS_HOST",
    )
)
REDIS_URL = os.getenv("REDIS_URL", _redis_url(0))
REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", _redis_url(1))
CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", _redis_url(2))

# Channel Layers với Redis cho real-time
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
            "capacity": env_int("CHANNEL_REDIS_CAPACITY", 1000),
            "expiry": env_int("CHANNEL_REDIS_EXPIRY", 60),
        },
    },
}

# EventStream Settings cho SSE
EVENTSTREAM_STORAGE_CLASS = "django_eventstream.storage.DjangoModelStorage"
NOTIFICATION_STREAM_MAX_CONNECTIONS_PER_USER = env_int(
    "NOTIFICATION_STREAM_MAX_CONNECTIONS_PER_USER", 2
)
NOTIFICATION_STREAM_POLL_SECONDS = env_int("NOTIFICATION_STREAM_POLL_SECONDS", 15)
NOTIFICATION_STREAM_MAX_DURATION_SECONDS = env_int(
    "NOTIFICATION_STREAM_MAX_DURATION_SECONDS", 300
)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "jobportal_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Asia/Ho_Chi_Minh")
os.environ["TZ"] = TIME_ZONE
if hasattr(time, "tzset"):
    time.tzset()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Cloudinary Storage
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}

if os.getenv("CLOUDINARY_CLOUD_NAME"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_URL = "/media/"  # Cloudinary handles the actual URL generation

    # Explicitly initialize Cloudinary SDK so direct cloudinary.uploader calls work
    import cloudinary

    cloudinary.config(
        cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
        api_key=os.getenv("CLOUDINARY_API_KEY"),
        api_secret=os.getenv("CLOUDINARY_API_SECRET"),
        secure=True,
    )
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core_users.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Pagination mặc định
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
    # Rate Limiting
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("DRF_THROTTLE_ANON", "2000/hour" if DEBUG else "100/hour"),
        "user": os.getenv("DRF_THROTTLE_USER", "5000/hour" if DEBUG else "1000/hour"),
        # Custom throttles
        "login": "5/minute",
        "token_refresh": "30/minute",
        "register": "10/hour",
        "password_reset": "3/hour",
        "email_verification": "3/hour",
        "social_auth": "10/minute",
        "two_factor_verify": "5/minute",
        "report_create": "5/hour",
        "burst": "60/minute",
        "sustained": "1000/day",
        "payment": "10/minute",
        "job_search": "60/minute",
        "application_submit": "20/hour",
        "notification_stream": "30/minute",
        "ai_matching": "20/hour",
        "file_upload": "30/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Exception handling
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
REMEMBER_ME_REFRESH_TOKEN_LIFETIME = timedelta(days=7)

SPECTACULAR_SETTINGS = {
    "TITLE": "JOBIO API",
    "DESCRIPTION": "OpenAPI schema for JOBIO recruitment platform.",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}

# ===== WebAuthn / Passkey Configuration =====
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID", "localhost")
WEBAUTHN_RP_NAME = os.getenv("WEBAUTHN_RP_NAME", "JobPortal")
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN", "http://localhost:4000")

# Dev defaults + production origins from env
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=(
        [
            "http://localhost:4000",
            "http://localhost:5173",  # Vite dev server
        ]
        if DEBUG
        else []
    ),
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        [
            "http://localhost:4000",
            "http://localhost:5173",
        ]
        if DEBUG
        else []
    ),
)

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", default=True)

if CORS_ALLOW_ALL_ORIGINS and CORS_ALLOW_CREDENTIALS:
    raise RuntimeError(
        "CORS_ALLOW_ALL_ORIGINS cannot be enabled while CORS_ALLOW_CREDENTIALS is true"
    )

if not DEBUG:
    if CORS_ALLOW_ALL_ORIGINS:
        raise RuntimeError("CORS_ALLOW_ALL_ORIGINS must be disabled when DEBUG=0")
    if not CORS_ALLOWED_ORIGINS:
        raise RuntimeError("CORS_ALLOWED_ORIGINS must be set when DEBUG=0")
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError("CSRF_TRUSTED_ORIGINS must be set when DEBUG=0")

# ===== Production Security Configuration =====
PRODUCTION_SECURITY_DEFAULT = not DEBUG
SECURE_SSL_REDIRECT = env_bool(
    "SECURE_SSL_REDIRECT", default=PRODUCTION_SECURITY_DEFAULT
)
SESSION_COOKIE_SECURE = env_bool(
    "SESSION_COOKIE_SECURE", default=PRODUCTION_SECURITY_DEFAULT
)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=PRODUCTION_SECURITY_DEFAULT)
SECURE_HSTS_SECONDS = env_int(
    "SECURE_HSTS_SECONDS", 31536000 if PRODUCTION_SECURITY_DEFAULT else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=PRODUCTION_SECURITY_DEFAULT
)
SECURE_HSTS_PRELOAD = env_bool(
    "SECURE_HSTS_PRELOAD", default=PRODUCTION_SECURITY_DEFAULT
)
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", default=False)
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = os.getenv(
    "SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin"
)
CONTENT_SECURITY_POLICY = os.getenv(
    "CONTENT_SECURITY_POLICY",
    "default-src 'self'; "
    "base-uri 'self'; "
    "object-src 'none'; "
    "frame-ancestors 'self'; "
    "img-src 'self' data: https:; "
    "media-src 'self' blob: https:; "
    "frame-src 'self' blob: https://res.cloudinary.com; "
    "script-src 'self' 'unsafe-inline'; "
    "style-src 'self' 'unsafe-inline'; "
    "connect-src 'self'",
)

if env_bool("USE_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ===== Email Configuration =====
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:4000")

# ===== VN Pay Configuration =====
VNP_TMN_CODE = os.getenv("VNP_TMN_CODE", "")
VNP_HASH_SECRET = os.getenv("VNP_HASH_SECRET", "")
VNP_URL = os.getenv("VNP_URL", "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html")
VNP_QUERY_URL = os.getenv(
    "VNP_QUERY_URL", "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
)
VNP_RETURN_URL = os.getenv(
    "VNP_RETURN_URL",
    "http://localhost:8000/api/billing/company-subscriptions/payment-return/",
)
VNP_FRONTEND_RETURN_URL = os.getenv(
    "VNP_FRONTEND_RETURN_URL", "http://localhost:4000/company/payment-result"
)
PAYMENT_PENDING_TIMEOUT_MINUTES = env_int("PAYMENT_PENDING_TIMEOUT_MINUTES", 5)
PAYMENT_PENDING_CLEANUP_INTERVAL_SECONDS = env_int(
    "PAYMENT_PENDING_CLEANUP_INTERVAL_SECONDS", 60
)

# ===== AI Configuration =====
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

RECOMMENDATION_SEMANTIC_ENABLED = env_bool(
    "RECOMMENDATION_SEMANTIC_ENABLED", default=True
)
RECOMMENDATION_EMBEDDING_PROVIDER = (
    os.getenv("RECOMMENDATION_EMBEDDING_PROVIDER", "local").strip().lower() or "local"
)
RECOMMENDATION_EMBEDDING_MODEL = os.getenv(
    "RECOMMENDATION_EMBEDDING_MODEL", "BAAI/bge-m3"
)
RECOMMENDATION_EMBEDDING_DIMENSIONS = env_int(
    "RECOMMENDATION_EMBEDDING_DIMENSIONS", 1024
)
RECOMMENDATION_SYNC_EMBEDDINGS = env_bool(
    "RECOMMENDATION_SYNC_EMBEDDINGS", default=False
)
RECOMMENDATION_VECTOR_STORE = (
    os.getenv("RECOMMENDATION_VECTOR_STORE", "pgvector").strip().lower() or "pgvector"
)
RECOMMENDATION_VECTOR_VERSION = os.getenv("RECOMMENDATION_VECTOR_VERSION", "v2")
RECOMMENDATION_REQUIRE_SAFETENSORS = env_bool(
    "RECOMMENDATION_REQUIRE_SAFETENSORS", default=True
)
RECOMMENDATION_TAXONOMY_VERSION = os.getenv(
    "RECOMMENDATION_TAXONOMY_VERSION", "taxonomy-v1"
)
RECOMMENDATION_PGVECTOR_EF_SEARCH = env_int("RECOMMENDATION_PGVECTOR_EF_SEARCH", 80)

MODERATION_ENABLED = env_bool("MODERATION_ENABLED", default=True)
MODERATION_PROVIDER = os.getenv("MODERATION_PROVIDER", "rule").strip().lower() or "rule"
MODERATION_TEXT_MODEL = os.getenv("MODERATION_TEXT_MODEL", "omni-moderation-latest")
MODERATION_IMAGE_MODEL = os.getenv("MODERATION_IMAGE_MODEL", MODERATION_TEXT_MODEL)
JOB_DOMAIN_MIN_CONFIDENCE = env_float("JOB_DOMAIN_MIN_CONFIDENCE", 0.85)

# Groq API — CV Parsing with LLM
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_API_KEYS = env_list("GROQ_API_KEYS", default=[])
for key_index in range(1, 11):
    extra_groq_api_key = os.getenv(f"GROQ_API_KEY_{key_index}", "")
    if extra_groq_api_key:
        GROQ_API_KEYS.append(extra_groq_api_key)
GROQ_CV_PARSER_MODEL = os.getenv("GROQ_CV_PARSER_MODEL", "openai/gpt-oss-120b")
GROQ_CV_PARSER_FALLBACK_MODEL = os.getenv(
    "GROQ_CV_PARSER_FALLBACK_MODEL", "llama-3.3-70b-versatile"
)
GROQ_CV_MODERATION_ENABLED = env_bool("GROQ_CV_MODERATION_ENABLED", default=True)
GROQ_CV_MODERATION_MODEL = os.getenv(
    "GROQ_CV_MODERATION_MODEL", "openai/gpt-oss-safeguard-20b"
)
GROQ_CV_MODERATION_MAX_OUTPUT_TOKENS = env_int(
    "GROQ_CV_MODERATION_MAX_OUTPUT_TOKENS", 256
)
GROQ_CV_PARSER_MAX_INPUT_CHARS = env_int("GROQ_CV_PARSER_MAX_INPUT_CHARS", 8000)
GROQ_CV_PARSER_MAX_OUTPUT_TOKENS = env_int("GROQ_CV_PARSER_MAX_OUTPUT_TOKENS", 2048)
CV_UPLOAD_MAX_BYTES = env_int("CV_UPLOAD_MAX_BYTES", 10 * 1024 * 1024)
CV_PDF_MAX_PAGES = env_int("CV_PDF_MAX_PAGES", 3)
CV_PARSE_ALLOWED_HOSTS = env_list(
    "CV_PARSE_ALLOWED_HOSTS", default=["res.cloudinary.com"]
)

# ===== Celery Configuration =====
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_RESULT_EXPIRES = env_int("CELERY_RESULT_EXPIRES", 60 * 60)
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_POOL_LIMIT = env_int("CELERY_BROKER_POOL_LIMIT", 10)
CELERY_WORKER_PREFETCH_MULTIPLIER = env_int("CELERY_WORKER_PREFETCH_MULTIPLIER", 1)
CELERY_TASK_ACKS_LATE = env_bool("CELERY_TASK_ACKS_LATE", default=True)
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_SOFT_TIME_LIMIT = env_int("CELERY_TASK_SOFT_TIME_LIMIT", 90)
CELERY_TASK_TIME_LIMIT = env_int("CELERY_TASK_TIME_LIMIT", 120)
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "default")
CELERY_TASK_ROUTES = {
    "apps.billing.tasks.send_payment_confirmation_email_task": {"queue": "emails"},
    "apps.billing.tasks.cleanup_expired_transactions": {"queue": "cleanup"},
    "apps.billing.tasks.cleanup_expired_subscriptions": {"queue": "cleanup"},
    "apps.communication.job_alerts.tasks.process_job_matching_task": {
        "queue": "matching"
    },
    "apps.recruitment.jobs.tasks.expire_published_jobs_task": {"queue": "cleanup"},
    "apps.system.file_uploads.tasks.delete_cloudinary_file_task": {"queue": "media"},
    "apps.candidate.recruiter_cvs.tasks.parse_cv_task": {"queue": "ai"},
    "apps.recruitment.jobs.tasks.generate_job_embedding_task": {"queue": "ai"},
    "apps.recruitment.jobs.tasks.generate_candidate_embedding_task": {"queue": "ai"},
}
CELERY_BROKER_VISIBILITY_TIMEOUT = env_int("CELERY_BROKER_VISIBILITY_TIMEOUT", 60 * 60)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": CELERY_BROKER_VISIBILITY_TIMEOUT,
    "socket_connect_timeout": env_float("CELERY_REDIS_CONNECT_TIMEOUT", 5.0),
    "socket_timeout": env_float("CELERY_REDIS_SOCKET_TIMEOUT", 5.0),
    "retry_on_timeout": True,
}
if CELERY_TASK_TIME_LIMIT and CELERY_BROKER_VISIBILITY_TIMEOUT < CELERY_TASK_TIME_LIMIT:
    raise RuntimeError(
        "CELERY_BROKER_VISIBILITY_TIMEOUT must be >= CELERY_TASK_TIME_LIMIT "
        "to avoid Redis redelivering long-running acknowledged-late tasks."
    )
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    "retry_policy": {
        "timeout": env_float("CELERY_REDIS_RESULT_TIMEOUT", 5.0),
    }
}
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-transactions": {
        "task": "apps.billing.tasks.cleanup_expired_transactions",
        "schedule": PAYMENT_PENDING_CLEANUP_INTERVAL_SECONDS,
    },
    "cleanup-expired-subscriptions": {
        "task": "apps.billing.tasks.cleanup_expired_subscriptions",
        "schedule": 60 * 60,
    },
    "expire-published-jobs": {
        "task": "apps.recruitment.jobs.tasks.expire_published_jobs_task",
        "schedule": 60 * 60,
    },
    "process-due-job-alerts": {
        "task": "apps.communication.job_alerts.tasks.process_due_job_alerts_task",
        "schedule": 60 * 60,
    },
}
# ===== Redis Cache Configuration =====
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": env_bool("REDIS_IGNORE_EXCEPTIONS", default=DEBUG),
            "SOCKET_CONNECT_TIMEOUT": env_float("REDIS_CONNECT_TIMEOUT", 5.0),
            "SOCKET_TIMEOUT": env_float("REDIS_SOCKET_TIMEOUT", 5.0),
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": env_int("REDIS_MAX_CONNECTIONS", 50),
            "CONNECTION_POOL_CLASS": "redis.connection.BlockingConnectionPool",
            "CONNECTION_POOL_CLASS_KWARGS": {
                "max_connections": env_int("REDIS_MAX_CONNECTIONS", 50),
                "timeout": env_float("REDIS_POOL_BLOCK_TIMEOUT", 20.0),
            },
            # Serialization
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "jobportal",
        "TIMEOUT": 60 * 30,  # 30 minutes default
    }
}

# Fallback to local memory cache in development if Redis not available
if DEBUG and not _REDIS_EXPLICITLY_CONFIGURED and not env_bool("USE_REDIS_CACHE"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Session engine using cache (optional - for performance)
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'

# ===== Logging Configuration =====
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "apps.billing.services.vnpay": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# # Import local settings to override default settings
# import os

# if os.getenv("USE_LOCAL_SETTINGS") == "True":
#     try:
#         from .local_settings import *
#     except ImportError:
#         pass
