# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_message_threads', '0001_initial'),
        ('recruitment_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='recruitment_applications.application', verbose_name='Đơn ứng tuyển liên quan'),
        ),
    ]
