# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('helpful', 'Hữu ích'), ('not_helpful', 'Không hữu ích'), ('report', 'Báo cáo')], max_length=20, verbose_name='Loại phản ứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Phản ứng đánh giá',
                'verbose_name_plural': 'Phản ứng đánh giá',
                'db_table': 'review_reactions',
            },
        ),
    ]
