# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
        ('company_media_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=500, verbose_name='URL media')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL thumbnail')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='company_companies.company', verbose_name='Công ty')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_media', to='company_media_types.mediatype', verbose_name='Loại media')),
            ],
            options={
                'verbose_name': 'Media công ty',
                'verbose_name_plural': 'Media công ty',
                'db_table': 'company_media',
                'ordering': ['display_order'],
            },
        ),
    ]
