# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_cv_template_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mẫu')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL ảnh thumbnail')),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL xem trước')),
                ('template_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mẫu')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='Mẫu cao cấp')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Số lần sử dụng')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Đánh giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='candidate_cv_template_categories.cvtemplatecategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Mẫu CV',
                'verbose_name_plural': 'Mẫu CV',
                'db_table': 'cv_templates',
            },
        ),
    ]
