# Generated by Django 5.2.12 on 2026-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cv_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtemplate',
            name='file_name',
            field=models.CharField(blank=True, help_text='Tên file HTML trong thư mục templates/cv/ (vd: modern.html)', max_length=100, null=True, verbose_name='Tên file HTML template'),
        ),
    ]
