# Generated by Django 5.2.12 on 2026-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_published_at_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Bài viết nổi bật"),
        ),
    ]
