# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_assessment_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssessmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Bắt buộc')),
                ('minimum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm tối thiểu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('assessment_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='assessment_assessment_tests.assessmenttest', verbose_name='Bài test')),
            ],
            options={
                'verbose_name': 'Yêu cầu test công việc',
                'verbose_name_plural': 'Yêu cầu test công việc',
                'db_table': 'job_assessment_requirements',
            },
        ),
    ]
