# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Tên trường')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bằng cấp')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chuyên ngành')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Đang học')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Học vấn',
                'verbose_name_plural': 'Học vấn',
                'db_table': 'recruiter_education',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
    ]
