# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái cũ')),
                ('new_status', models.CharField(max_length=50, verbose_name='Trạng thái mới')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'db_table': 'application_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
