# Generated by Django 5.2.10 on 2026-01-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Hành động')),
                ('entity_type', models.CharField(db_index=True, max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Giá trị cũ')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Giá trị mới')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
