# Generated by Django 5.2.10 on 2026-03-02 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_message_threads', '0004_messagethread_last_message_at_and_more'),
        ('communication_messages', '0002_delete_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Tệp đính kèm')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='Tin nhắn hệ thống')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication_message_threads.messagethread', verbose_name='Chuỗi tin nhắn')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='idx_msg_thread_created'), models.Index(fields=['sender', 'created_at'], name='idx_msg_sender_created')],
            },
        ),
    ]
