# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Tham gia lúc')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Đọc lần cuối')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Người tham gia tin nhắn',
                'verbose_name_plural': 'Người tham gia tin nhắn',
                'db_table': 'message_participants',
            },
        ),
    ]
