# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_message_participants', '0001_initial'),
        ('communication_message_threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparticipant',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication_message_threads.messagethread', verbose_name='Chuỗi tin nhắn'),
        ),
        migrations.AddField(
            model_name='messageparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_participations', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia'),
        ),
        migrations.AlterUniqueTogether(
            name='messageparticipant',
            unique_together={('thread', 'user')},
        ),
    ]
