# Generated by Django 5.2.10 on 2026-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_message_participants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparticipant',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='Số tin nhắn chưa đọc'),
        ),
    ]
