# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiters', '0001_initial'),
        ('geography_provinces', '0001_initial'),
        ('recruitment_job_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=255, verbose_name='Tên thông báo')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Từ khóa')),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Toàn thời gian'), ('part-time', 'Bán thời gian'), ('contract', 'Hợp đồng'), ('internship', 'Thực tập'), ('freelance', 'Tự do')], max_length=20, null=True, verbose_name='Loại công việc')),
                ('level', models.CharField(blank=True, choices=[('intern', 'Thực tập sinh'), ('fresher', 'Fresher'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Team Lead'), ('manager', 'Manager'), ('director', 'Director')], max_length=20, null=True, verbose_name='Cấp bậc')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối thiểu')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối đa')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('frequency', models.CharField(choices=[('instant', 'Ngay lập tức'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần')], default='daily', max_length=20, verbose_name='Tần suất')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gửi lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='recruitment_job_categories.jobcategory', verbose_name='Danh mục')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='geography_provinces.province', verbose_name='Tỉnh/Thành phố')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='candidate_recruiters.recruiter', verbose_name='Ứng viên')),
            ],
            options={
                'verbose_name': 'Thông báo việc làm',
                'verbose_name_plural': 'Thông báo việc làm',
                'db_table': 'job_alerts',
            },
        ),
    ]
