# Generated by Codex on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("communication_notifications", "0002_notification_updated_at"),
        ("core_users", "0006_rename_role_recruiter_to_candidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email"),
                ),
                (
                    "push_notifications",
                    models.BooleanField(default=True, verbose_name="Push"),
                ),
                (
                    "job_alerts",
                    models.BooleanField(
                        default=True, verbose_name="Thông báo việc làm"
                    ),
                ),
                (
                    "application_updates",
                    models.BooleanField(
                        default=True, verbose_name="Cập nhật ứng tuyển"
                    ),
                ),
                (
                    "message_notifications",
                    models.BooleanField(default=True, verbose_name="Tin nhắn"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to="core_users.customuser",
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cài đặt thông báo",
                "verbose_name_plural": "Cài đặt thông báo",
                "db_table": "notification_preferences",
            },
        ),
    ]
