# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiters', '0001_initial'),
        ('company_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá chung')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='Điểm mạnh')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Điểm yếu')),
                ('work_environment_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá môi trường làm việc')),
                ('salary_benefits_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá lương thưởng')),
                ('management_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá quản lý')),
                ('career_development_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá phát triển sự nghiệp')),
                ('employment_status', models.CharField(blank=True, choices=[('current', 'Nhân viên hiện tại'), ('former', 'Nhân viên cũ'), ('intern', 'Thực tập sinh')], max_length=20, null=True, verbose_name='Trạng thái làm việc')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí')),
                ('employment_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Thời gian làm việc')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Ẩn danh')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Số lượt hữu ích')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='company_companies.company', verbose_name='Công ty')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='candidate_recruiters.recruiter', verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá công ty',
                'verbose_name_plural': 'Đánh giá công ty',
                'db_table': 'reviews',
            },
        ),
    ]
