# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('project_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL dự án')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_ongoing', models.BooleanField(default=False, verbose_name='Đang thực hiện')),
                ('technologies_used', models.TextField(blank=True, null=True, verbose_name='Công nghệ sử dụng')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dự án cá nhân',
                'verbose_name_plural': 'Dự án cá nhân',
                'db_table': 'recruiter_projects',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
    ]
