# Generated by Django 5.2.10 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_assessment_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AddField(
            model_name='assessmentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
