# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiter_cvs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Thư xin việc')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('shortlisted', 'Vào vòng tiếp'), ('interview', 'Phỏng vấn'), ('offered', 'Đề xuất offer'), ('rejected', 'Từ chối'), ('withdrawn', 'Đã rút'), ('accepted', 'Đã nhận việc')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày ứng tuyển')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xem xét')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='candidate_recruiter_cvs.recruitercv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'db_table': 'applications',
            },
        ),
    ]
