# Generated by Django 5.2.10 on 2026-03-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography_provinces', '0002_province_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province_code',
        ),
    ]
