# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('basic', 'Cơ bản'), ('intermediate', 'Trung bình'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên gia')], default='intermediate', max_length=20, verbose_name='Mức độ thành thạo')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Số năm kinh nghiệm')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('endorsement_count', models.IntegerField(default=0, verbose_name='Số lượt xác nhận')),
                ('last_used_date', models.DateField(blank=True, null=True, verbose_name='Ngày sử dụng gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Kỹ năng ứng viên',
                'verbose_name_plural': 'Kỹ năng ứng viên',
                'db_table': 'recruiter_skills',
            },
        ),
    ]
