# Generated by Django 6.0.1 on 2026-01-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography_provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(max_length=100, verbose_name='Tên xã/phường')),
                ('commune_type', models.CharField(choices=[('commune', 'Xã'), ('ward', 'Phường'), ('township', 'Thị trấn'), ('special_zone', 'Đơn vị hành chính đặc biệt')], max_length=20, verbose_name='Loại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='geography_provinces.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Xã/Phường/Thị trấn',
                'verbose_name_plural': 'Xã/Phường/Thị trấn',
                'db_table': 'communes',
                'ordering': ['commune_name'],
            },
        ),
    ]
