# Generated by Django 5.2.10 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography_communes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="commune_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Mã xã/phường",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
    ]
