# Generated by Django 5.2.11 on 2026-03-19 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geography_communes", "0002_commune_commune_code_commune_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="commune_code",
        ),
    ]
