# Generated by Django 6.0.1 on 2026-01-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='Tên loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('severity', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('error', 'Lỗi'), ('critical', 'Nghiêm trọng')], default='info', max_length=20, verbose_name='Mức độ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Loại hoạt động',
                'verbose_name_plural': 'Loại hoạt động',
                'db_table': 'activity_log_types',
            },
        ),
    ]
