# Generated by Django 6.0.1 on 2026-01-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_benefit_categories', '0001_initial'),
        ('company_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=255, verbose_name='Tên phúc lợi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_benefits', to='company_benefit_categories.benefitcategory', verbose_name='Danh mục')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='company_companies.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Phúc lợi công ty',
                'verbose_name_plural': 'Phúc lợi công ty',
                'db_table': 'company_benefits',
                'ordering': ['display_order'],
            },
        ),
    ]
