# Generated by Django 5.2.10 on 2026-03-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_users", "0003_customuser_social_id_customuser_social_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasskey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(
                        help_text="WebAuthn credential ID (binary)",
                        unique=True,
                        verbose_name="Credential ID",
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(
                        help_text="CBOR-encoded COSE public key",
                        verbose_name="Public Key",
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Signature counter for replay attack protection",
                        verbose_name="Sign Count",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="Passkey",
                        help_text="Tên do người dùng đặt (ví dụ: MacBook Touch ID)",
                        max_length=255,
                        verbose_name="Tên thiết bị",
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authenticator Attestation GUID",
                        max_length=36,
                        verbose_name="AAGUID",
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách transport types (usb, ble, nfc, internal, hybrid)",
                        verbose_name="Transports",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần sử dụng cuối"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey",
                "verbose_name_plural": "Passkeys",
                "db_table": "user_passkeys",
                "ordering": ["-created_at"],
            },
        ),
    ]
