# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography_addresses', '0001_initial'),
        ('recruitment_applications', '0001_initial'),
        ('recruitment_interview_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1, verbose_name='Vòng phỏng vấn')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Thời gian phỏng vấn')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Thời lượng (phút)')),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link meeting')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('rescheduled', 'Đổi lịch'), ('no-show', 'Không tham gia')], db_index=True, default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('result', models.CharField(choices=[('pass', 'Đạt'), ('fail', 'Không đạt'), ('pending', 'Chờ kết quả')], default='pending', max_length=20, verbose_name='Kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='geography_addresses.address', verbose_name='Địa điểm')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment_applications.application', verbose_name='Đơn ứng tuyển')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('interview_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment_interview_types.interviewtype', verbose_name='Loại phỏng vấn')),
            ],
            options={
                'verbose_name': 'Phỏng vấn',
                'verbose_name_plural': 'Phỏng vấn',
                'db_table': 'interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
