# Generated by Django 5.2.13 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recruitment_interviews",
            "0003_interview_interviewer_interview_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Đã lên lịch"),
                    ("confirmed", "Đã xác nhận"),
                    ("in_progress", "Đang diễn ra"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                    ("rescheduled", "Đổi lịch"),
                    ("no-show", "Không tham gia"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
