# Generated by Django 5.2.10 on 2026-01-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0002_allow_null_user'),
        ('recruitment_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Campaign Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='company_companies.company', verbose_name='Company')),
                ('jobs', models.ManyToManyField(blank=True, related_name='campaigns', to='recruitment_jobs.job', verbose_name='Jobs')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'recruitment_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
