# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, unique=True, verbose_name='Tên phương thức')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('icon_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
                'db_table': 'payment_methods',
                'ordering': ['display_order'],
            },
        ),
    ]
