# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Tên chiến dịch')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ngân sách')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('target_positions', models.IntegerField(default=0, verbose_name='Số vị trí mục tiêu')),
                ('hired_count', models.IntegerField(default=0, verbose_name='Số đã tuyển')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='company_companies.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Chiến dịch tuyển dụng',
                'verbose_name_plural': 'Chiến dịch tuyển dụng',
                'db_table': 'recruitment_campaigns',
            },
        ),
    ]
