# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_industries', '0001_initial'),
        ('geography_addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('job_title', models.CharField(max_length=100, verbose_name='Chức danh')),
                ('start_date', models.DateField(db_index=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Công việc hiện tại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Thành tựu')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_experiences', to='geography_addresses.address', verbose_name='Địa chỉ')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_experiences', to='company_industries.industry', verbose_name='Ngành nghề')),
            ],
            options={
                'verbose_name': 'Kinh nghiệm làm việc',
                'verbose_name_plural': 'Kinh nghiệm làm việc',
                'db_table': 'recruiter_experience',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
    ]
