# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
        ('geography_addresses', '0001_initial'),
        ('recruitment_job_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('job_type', models.CharField(choices=[('full-time', 'Toàn thời gian'), ('part-time', 'Bán thời gian'), ('contract', 'Hợp đồng'), ('internship', 'Thực tập'), ('freelance', 'Tự do')], max_length=20, verbose_name='Loại công việc')),
                ('level', models.CharField(choices=[('intern', 'Thực tập sinh'), ('fresher', 'Fresher'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Team Lead'), ('manager', 'Manager'), ('director', 'Director')], max_length=20, verbose_name='Cấp bậc')),
                ('experience_years_min', models.IntegerField(default=0, verbose_name='Kinh nghiệm tối thiểu (năm)')),
                ('experience_years_max', models.IntegerField(blank=True, null=True, verbose_name='Kinh nghiệm tối đa (năm)')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối thiểu')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương tối đa')),
                ('salary_currency', models.CharField(default='VND', max_length=10, verbose_name='Đơn vị tiền tệ')),
                ('salary_type', models.CharField(choices=[('monthly', 'Theo tháng'), ('yearly', 'Theo năm'), ('hourly', 'Theo giờ'), ('project', 'Theo dự án')], default='monthly', max_length=20, verbose_name='Loại lương')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='Lương thỏa thuận')),
                ('number_of_positions', models.IntegerField(default=1, verbose_name='Số lượng tuyển')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Quyền lợi')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Làm việc từ xa')),
                ('application_deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Hạn nộp hồ sơ')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã đăng'), ('closed', 'Đã đóng'), ('expired', 'Hết hạn')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('view_count', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('application_count', models.IntegerField(default=0, verbose_name='Số đơn ứng tuyển')),
                ('featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('featured_until', models.DateField(blank=True, null=True, verbose_name='Nổi bật đến')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ngày đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='geography_addresses.address', verbose_name='Địa chỉ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='recruitment_job_categories.jobcategory', verbose_name='Danh mục')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company_companies.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Việc làm',
                'verbose_name_plural': 'Việc làm',
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['company', 'status'], name='idx_jobs_company_status'), models.Index(fields=['category', 'status'], name='idx_jobs_category_status')],
            },
        ),
    ]
