# Generated by Django 5.2.10 on 2026-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment_jobs", "0002_job_idx_jobs_title_desc_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Toàn thời gian"),
                    ("part-time", "Bán thời gian"),
                    ("contract", "Hợp đồng"),
                    ("internship", "Thực tập"),
                    ("freelance", "Tự do"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Loại công việc",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Thực tập sinh"),
                    ("fresher", "Fresher"),
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Team Lead"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Cấp bậc",
            ),
        ),
    ]
