# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5, verbose_name='Điểm tổng')),
                ('skill_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm kỹ năng')),
                ('experience_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm kinh nghiệm')),
                ('education_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm học vấn')),
                ('location_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm vị trí')),
                ('salary_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm lương')),
                ('matching_details', models.JSONField(blank=True, null=True, verbose_name='Chi tiết matching')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tính toán')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
            ],
            options={
                'verbose_name': 'Điểm AI matching',
                'verbose_name_plural': 'Điểm AI matching',
                'db_table': 'ai_matching_scores',
                'ordering': ['-overall_score'],
            },
        ),
    ]
