# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_ai_matching_scores', '0001_initial'),
        ('candidate_recruiters', '0001_initial'),
        ('recruitment_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatchingscore',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scores', to='recruitment_jobs.job', verbose_name='Công việc'),
        ),
        migrations.AddField(
            model_name='aimatchingscore',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scores', to='candidate_recruiters.recruiter', verbose_name='Ứng viên'),
        ),
        migrations.AlterUniqueTogether(
            name='aimatchingscore',
            unique_together={('job', 'recruiter')},
        ),
    ]
