# Generated by Django 5.2.10 on 2026-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_transaction_ip_address_transaction_vnp_bankcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
