# Generated by Django 5.2.10 on 2026-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_referrals', '0002_referral_paid_at_referralprogram_reward_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=20),
        ),
    ]
