# Generated by Django 6.0.1 on 2026-01-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography_communes', '0001_initial'),
        ('geography_provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255, verbose_name='Số nhà, tên đường')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Kinh độ')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='geography_communes.commune', verbose_name='Xã/Phường')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='geography_provinces.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'db_table': 'addresses',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_location')],
            },
        ),
    ]
