# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('original_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('file_path', models.CharField(max_length=500, verbose_name='Đường dẫn file')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại file')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Kích thước (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME type')),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại đối tượng')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'File upload',
                'verbose_name_plural': 'File upload',
                'db_table': 'file_uploads',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_file_entity')],
            },
        ),
    ]
