# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá')),
                ('currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD')], max_length=10, verbose_name='Đơn vị tiền tệ')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý'), ('yearly', 'Hàng năm')], max_length=20, verbose_name='Chu kỳ thanh toán')),
                ('duration_days', models.IntegerField(verbose_name='Thời hạn (ngày)')),
                ('max_job_posts', models.IntegerField(blank=True, null=True, verbose_name='Số tin tuyển dụng tối đa')),
                ('max_featured_jobs', models.IntegerField(default=0, verbose_name='Số tin nổi bật tối đa')),
                ('max_urgent_jobs', models.IntegerField(default=0, verbose_name='Số tin gấp tối đa')),
                ('can_view_candidate_contact', models.BooleanField(default=False, verbose_name='Xem liên hệ ứng viên')),
                ('can_use_ai_matching', models.BooleanField(default=False, verbose_name='Sử dụng AI matching')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Hỗ trợ ưu tiên')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Tính năng')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Phổ biến')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Gói đăng ký',
                'verbose_name_plural': 'Gói đăng ký',
                'db_table': 'subscription_plans',
                'ordering': ['display_order'],
            },
        ),
    ]
