# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiter_languages', '0001_initial'),
        ('candidate_recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterlanguage',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidate_recruiters.recruiter', verbose_name='Ứng viên'),
        ),
        migrations.AlterUniqueTogether(
            name='recruiterlanguage',
            unique_together={('recruiter', 'language')},
        ),
    ]
