# Generated by Django 5.2.10 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_recruiter_languages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterlanguage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
