# Generated by Django 5.2.14 on 2026-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_recruiter_languages", "0003_recruiterlanguage_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterlanguage",
            name="is_native",
            field=models.BooleanField(default=False, verbose_name="Ngôn ngữ chính"),
        ),
    ]
