# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment_campaign_jobs', '0001_initial'),
        ('recruitment_jobs', '0001_initial'),
        ('recruitment_recruitment_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignjob',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_jobs', to='recruitment_recruitment_campaigns.recruitmentcampaign', verbose_name='Chiến dịch'),
        ),
        migrations.AddField(
            model_name='campaignjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_jobs', to='recruitment_jobs.job', verbose_name='Công việc'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignjob',
            unique_together={('campaign', 'job')},
        ),
    ]
