# Generated by Django 5.2.10 on 2026-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment_saved_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
    ]
