# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('blocked', 'Đã chặn')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to='candidate_recruiters.recruiter', verbose_name='Người nhận lời mời')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to='candidate_recruiters.recruiter', verbose_name='Người gửi lời mời')),
            ],
            options={
                'verbose_name': 'Kết nối',
                'verbose_name_plural': 'Kết nối',
                'db_table': 'recruiter_connections',
                'unique_together': {('requester', 'receiver')},
            },
        ),
    ]
