# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thưởng')),
                ('bonus_currency', models.CharField(default='VND', max_length=10, verbose_name='Đơn vị tiền tệ')),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Điều khoản và điều kiện')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programs', to='company_companies.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Chương trình giới thiệu',
                'verbose_name_plural': 'Chương trình giới thiệu',
                'db_table': 'referral_programs',
            },
        ),
    ]
