# Generated by Django 5.2.13 on 2026-04-28 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0002_alter_emailtemplate_is_active_alter_sentemail_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="category",
        ),
        migrations.RemoveField(
            model_name="sentemail",
            name="template",
        ),
        migrations.DeleteModel(
            name="EmailTemplateCategory",
        ),
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.DeleteModel(
            name="SentEmail",
        ),
    ]
