# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_blog_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('featured_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh đại diện')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã đăng'), ('archived', 'Lưu trữ')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('view_count', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ngày đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog_blog_categories.blogcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
