# Generated by Django 5.2.13 on 2026-04-19 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system_report_types", "0002_reporttype_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Loại đối tượng"
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(db_index=True, verbose_name="ID đối tượng"),
                ),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "evidence_urls",
                    models.JSONField(
                        blank=True, null=True, verbose_name="URL bằng chứng"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("reviewing", "Đang xem xét"),
                            ("resolved", "Đã giải quyết"),
                            ("rejected", "Từ chối"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xử lý"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="system_report_types.reporttype",
                        verbose_name="Loại báo cáo",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người báo cáo",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xử lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Báo cáo vi phạm",
                "verbose_name_plural": "Báo cáo vi phạm",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
