# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_assessment_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('test_type', models.CharField(choices=[('skill', 'Kỹ năng'), ('personality', 'Tính cách'), ('aptitude', 'Năng khiếu'), ('language', 'Ngôn ngữ'), ('technical', 'Kỹ thuật')], db_index=True, max_length=20, verbose_name='Loại bài test')),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Cơ bản'), ('intermediate', 'Trung bình'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên gia')], max_length=20, null=True, verbose_name='Độ khó')),
                ('duration_minutes', models.IntegerField(verbose_name='Thời lượng (phút)')),
                ('total_questions', models.IntegerField(verbose_name='Tổng số câu hỏi')),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm đạt')),
                ('questions_data', models.JSONField(verbose_name='Dữ liệu câu hỏi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='assessment_assessment_categories.assessmentcategory', verbose_name='Danh mục')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bài test',
                'verbose_name_plural': 'Bài test',
                'db_table': 'assessment_tests',
            },
        ),
    ]
