# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiters', '0001_initial'),
        ('company_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày theo dõi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='company_companies.company', verbose_name='Công ty')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to='candidate_recruiters.recruiter', verbose_name='Người theo dõi')),
            ],
            options={
                'verbose_name': 'Người theo dõi công ty',
                'verbose_name_plural': 'Người theo dõi công ty',
                'db_table': 'company_followers',
                'unique_together': {('company', 'recruiter')},
            },
        ),
    ]
