# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_email_template_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('subject', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Biến')),
                ('is_system', models.BooleanField(default=False, verbose_name='Mẫu hệ thống')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='email_email_template_categories.emailtemplatecategory', verbose_name='Danh mục')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Mẫu email',
                'verbose_name_plural': 'Mẫu email',
                'db_table': 'email_templates',
            },
        ),
    ]
