# Generated by Django 5.2.10 on 2026-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Danh mục')),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Trả lời')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('view_count', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Lượt hữu ích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp',
                'verbose_name_plural': 'Câu hỏi thường gặp',
                'db_table': 'faqs',
                'ordering': ['display_order'],
            },
        ),
    ]
