# Generated by Django 5.2.10 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255, verbose_name='Tên chứng chỉ')),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tổ chức cấp')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày hết hạn')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã chứng chỉ')),
                ('credential_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL xác minh')),
                ('does_not_expire', models.BooleanField(default=False, verbose_name='Không hết hạn')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chứng chỉ',
                'verbose_name_plural': 'Chứng chỉ',
                'db_table': 'recruiter_certifications',
                'ordering': ['-issue_date', 'display_order'],
            },
        ),
    ]
