# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0001_initial'),
        ('system_report_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period_start', models.DateField(verbose_name='Ngày bắt đầu')),
                ('report_period_end', models.DateField(verbose_name='Ngày kết thúc')),
                ('metrics', models.JSONField(verbose_name='Số liệu')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='company_companies.company', verbose_name='Công ty')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='system_report_types.reporttype', verbose_name='Loại báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo thống kê',
                'verbose_name_plural': 'Báo cáo thống kê',
                'db_table': 'analytics_reports',
                'indexes': [models.Index(fields=['report_period_start', 'report_period_end'], name='idx_report_period')],
            },
        ),
    ]
