# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_recruiters', '0001_initial'),
        ('recruitment_jobs', '0001_initial'),
        ('social_referral_programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email ứng viên')),
                ('referred_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên ứng viên')),
                ('referred_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('contacted', 'Đã liên hệ'), ('applied', 'Đã ứng tuyển'), ('interviewed', 'Đã phỏng vấn'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Số tiền thưởng')),
                ('bonus_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('bonus_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='recruitment_jobs.job', verbose_name='Công việc')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='social_referral_programs.referralprogram', verbose_name='Chương trình')),
                ('referred_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to='candidate_recruiters.recruiter', verbose_name='Ứng viên được giới thiệu')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Người giới thiệu')),
            ],
            options={
                'verbose_name': 'Giới thiệu ứng viên',
                'verbose_name_plural': 'Giới thiệu ứng viên',
                'db_table': 'referrals',
            },
        ),
    ]
