# Generated by Django 6.0.1 on 2026-01-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_industries', '0001_initial'),
        ('geography_addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Tên công ty')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã số thuế')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 nhân viên'), ('11-50', '11-50 nhân viên'), ('51-200', '51-200 nhân viên'), ('201-500', '201-500 nhân viên'), ('501-1000', '501-1000 nhân viên'), ('1000+', 'Trên 1000 nhân viên')], max_length=20, null=True, verbose_name='Quy mô công ty')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL logo')),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL banner')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Năm thành lập')),
                ('verification_status', models.CharField(choices=[('pending', 'Chờ xác minh'), ('verified', 'Đã xác minh'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái xác minh')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác minh')),
                ('follower_count', models.IntegerField(default=0, verbose_name='Số người theo dõi')),
                ('job_count', models.IntegerField(default=0, verbose_name='Số việc làm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='geography_addresses.address', verbose_name='Địa chỉ')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='company_industries.industry', verbose_name='Ngành nghề')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL, verbose_name='Người xác minh')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'db_table': 'companies',
            },
        ),
    ]
