# Generated by Django 5.2.10 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_companies", "0002_allow_null_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email liên hệ"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Số điện thoại"
            ),
        ),
    ]
