# Generated by Django 5.2.10 on 2026-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_companies", "0003_company_email_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 nhân viên"),
                    ("11-50", "11-50 nhân viên"),
                    ("51-200", "51-200 nhân viên"),
                    ("201-500", "201-500 nhân viên"),
                    ("501-1000", "501-1000 nhân viên"),
                    ("1000+", "Trên 1000 nhân viên"),
                ],
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Quy mô công ty",
            ),
        ),
    ]
