# Generated by Django 5.2.10 on 2026-01-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_subscription_plans', '0001_initial'),
        ('company_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(db_index=True, verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy'), ('suspended', 'Tạm dừng')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Tự động gia hạn')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thanh toán')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số tiền giảm giá')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền cuối cùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='company_companies.company', verbose_name='Công ty')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing_subscription_plans.subscriptionplan', verbose_name='Gói đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký công ty',
                'verbose_name_plural': 'Đăng ký công ty',
                'db_table': 'company_subscriptions',
            },
        ),
    ]
